### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by valaparthvi** [rancher/hosted-providers-e2e#11]
Update the base README with the following:
- [ ] A note about which part of rancher, this repo covers, i.e. hosted providers.
- [ ] Cloud and Credentials configuration for all the hosted providers.
- [x] Ginkgo and Makefile commands to run the tests.
- [ ] ~Provider specific and common `helpers`~
- [ ] ~Adding new tests and where to put them.~
- [ ] GitHub Actions and how to trigger them.
- [x] Automated readme script (#20)

**Comment by cpinjani** [comment]
@valaparthvi Can this closed if done ?
