### ISSUE TITLE
v2.9 - Analyze and fix failing jobs

### ISSUE THREAD

**Issue by cpinjani** [rancher/hosted-providers-e2e#117]
- GKE support_matrix_provisioning: https://github.com/rancher/hosted-providers-e2e/actions/runs/9478298953, k8s_chart_support: https://github.com/rancher/hosted-providers-e2e/actions/runs/9486026270
- EKS k8s_chart_support: https://github.com/rancher/hosted-providers-e2e/actions/runs/9486027541/job/26165705901,
p0_importing: https://github.com/rancher/hosted-providers-e2e/actions/runs/9477951949 (failing on v2.8 also)

**Comment by valaparthvi** [comment]
>AKS: k8s_chart_support: https://github.com/rancher/hosted-providers-e2e/actions/runs/9468789286

K8s chart support are not designed to work with operator nightly charts.
