### ISSUE TITLE
Improving GitHub Actions

### ISSUE THREAD

**Issue by valaparthvi** [rancher/hosted-providers-e2e#16]
PR #14 fixed issues with GitHub Action, it helped us understand that the same ephemeral self hosted runner cannot be used for multiple jobs in a workflow, which is why we converted the jobs to steps, but there were other issues introduced with this approach, for e.g.
1. If one of the (test) step fails, all the consequent test steps will also fail.
2. All the test steps cannot be run in parallel.

Things that can be improved here is:
- [ ] 1. None of the 4 test steps must be dependent on each other, if one fails the others should continue to run. `continue-on-error:true` is a good way to continue even if there was an error, but the end result is always indicated by the status of last step. So if step 3 fails, but step 4 passes, the final status will be a :green_circle:. This might be fine, because we do see these errors in the summary. (Ref: https://github.com/rancher/hosted-providers-e2e/actions/runs/7795363879)
- [ ] 2. The possibility to run all the 4 test suites in parallel.

**Comment by cpinjani** [comment]
Running GH Actions steps in parallel not yet supported.
Ref: https://github.com/orgs/community/discussions/26291
