### ISSUE TITLE
Setup Cleanup jobs

### ISSUE THREAD

**Issue by valaparthvi** [rancher/hosted-providers-e2e#68]
Sometimes when tests fails, resources are left behind. This is especially a problem with Amazon since there is a limit on the number of resources that can be created.
A GH Action must be setup to run nightly to clean the resources.

**Amazon cleanup**:
1. Fetch the cloudformation stacks. `aws cloudformation list-stacks`
2. Filter the ones with `auto-ekshostcluster` in the name.
3. Delete the stacks.
4. Repeat the same for clusters and launch templates.

**Azure/Google cleanup**:
This might not be necessary but we do it regardless.
1. Get a filtered list of the clusters.
`gcloud container clusters list --filter auto-gkehostcluster` OR `az aks list`.
2. Delete the clusters.

We can use `jq` to filter the names.
This job must be run nightly as to not disturb the tests being run; it should also be possible to trigger it manually.

**Comment by cpinjani** [comment]
For AWS, we can make use of https://github.com/rancher-sandbox/aws-janitor
