### ISSUE TITLE
DOWNSTREAM_CLUSTER_CLEANUP should be true by default

### ISSUE THREAD

**Issue by valaparthvi** [rancher/hosted-providers-e2e#79]
The default behavior we want is to cleanup clusters, so it makes sense to set the default value for DOWNSTREAM_CLUSTER_CLEANUP to be true.

**Comment by cpinjani** [comment]
Seems its already implemented: https://github.com/rancher/hosted-providers-e2e/blob/9df8c7fa6a5691a922d2df1737a7fdc9e9d83341/.github/workflows/aks.yaml#L68

**Comment by valaparthvi** [comment]
At the time, I meant not just for the GH action, but for local test runs too. But the current behavior is fine too.
